{% set name = "stonesoup" %}
{% set version = "0.1b5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bec39d071ee10637c08515b5bdb898357e77b803dabb78add4b9aed031781c13

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools-scm
    - setuptools_scm_git_archive
  run:
    - python >=3.6
    - matplotlib-base
    - numpy >=1.17
    - pymap3d
    - ruamel.yaml >=0.15.45
    - scipy
    - setuptools >=42
    - utm

test:
  imports:
    - stonesoup
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dstl/Stone-Soup
  license: MIT
  license_file: LICENSE
  summary: 'A tracking and state estimation framework'
  description: |
    Stone Soup is a software project to provide the target tracking and
    state estimation community with a framework for the development and
    testing of tracking and state estimation algorithms.
  doc_url: https://stonesoup.rtfd.io/en/v{{ version }}/
  dev_url: https://github.com/dstl/Stone-Soup

extra:
  recipe-maintainers:
    - sdhiscocks
